### ISSUE TITLE
Heroku seems to have had enough of saliens (suspending accounts)

### ISSUE THREAD

**Issue by ambjorn0** [South-Paw/salien-script-js#44] opened 2018-06-29 14:02 UTC
Seems like Heroku is suspending accounts running the salien script.
I had my account suspended just recently and I'm not alone.

![heroku](https://user-images.githubusercontent.com/29261575/42096464-b10d0e68-7bb5-11e8-80de-9481075c5d2d.png)
They suspended it three times even...

**Comment by resir014** [comment] 2018-06-29 14:25
Duplicate of #36.

**Closed as completed by resir014** 2018-06-29 14:25 UTC
Labels: duplicate, wontfix
