### ISSUE TITLE
Heroku suspend script : Process exited with status 143

### ISSUE THREAD

**Issue by GitSeal** [South-Paw/salien-script-js#36] opened 2018-06-28 12:57 UTC
2018-06-28T12:25:25.096904+00:00 heroku[salien.1]: State changed from up to down
2018-06-28T12:25:25.748685+00:00 heroku[salien.1]: Stopping all processes with SIGTERM
2018-06-28T12:25:25.848963+00:00 heroku[salien.1]: Process exited with status 143

**Comment by ACast59** [comment] 2018-06-28 13:00
This is happening to me as well. I deleted the app and deployed it again, it's working now.

**Comment by GitSeal** [comment] 2018-06-28 13:08
please help us

**Comment by hdk5** [comment] 2018-06-28 14:14
Probably, heroku just started banning saliens bots. Redeploying app should fix the problem for some time, but you may also be suspended again soon.

Well, I guess I am moving to Azure

**Comment by South-Paw** [comment] 2018-06-28 14:16
Not a bug with the bot itself so closing issue - we can't control what heroku does.

**Comment by South-Paw** [comment] 2018-06-29 05:18
Turns out its to do with user agent string we provide in requests, @hdk5 has kindly fixed it.

So this issue is fix with #41 if we merge it...

**Closed as completed** 2018-06-30 08:57 UTC
Labels: bug

**Comment by South-Paw** [comment] 2018-06-30 08:58
Update: Heroku is no longer allowing scripts from what I'm told so removing it from the readme & files
